### ISSUE TITLE
End invalid here? Should be EndVar?

### ISSUE THREAD

**Issue by twfs** [PascaDiMagliano-Lab/MultimodalMappingPDA-scRNASeq#1]
https://github.com/PascaDiMagliano-Lab/MultimodalMappingPDA-scRNASeq/blob/654f5d8723c522059b239afd5031a905cf8db15b/R%20Code/MultimodalMappingPDA-scRNASeq.R#L1144

**Comment by PascaDiMagliano-Lab** [comment]
Thank you for noticing, updated.
